// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uQ1tStPUiuweYuxMksqyYP
// Component: 35BKfOaVUOBWYU
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";
import { SupabaseMutation } from "../../CodeComponents/DatabaseComponents"; // plasmic-import: -f1Kq0-fPBNYLK/codeComponent
import { FormContextComponent } from "../../CodeComponents/Form"; // plasmic-import: mBmhM2W1BTyu1_/codeComponent
import { FormTextInput } from "../../CodeComponents/Form"; // plasmic-import: NUsTWjb3PzOqdi/codeComponent
import TextInput from "../../TextInput"; // plasmic-import: J9zrw5ApeikFt/component
import Button from "../../Button"; // plasmic-import: IELNbHKEGo49X/component

import { useScreenVariants as useScreenVariants_52Cioa0UnGfvY1 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 52cioa0UNGfvY1/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_supabase_tutorial_refreshed.module.css"; // plasmic-import: uQ1tStPUiuweYuxMksqyYP/projectcss
import sty from "./PlasmicAddEntry.module.css"; // plasmic-import: 35BKfOaVUOBWYU/css

import SearchsvgIcon from "./icons/PlasmicIcon__Searchsvg"; // plasmic-import: lTuEpwKUST6iVJ/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: DGsq-C17D8eHoS/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: bpL7QDrSKQF7Lo/icon

export type PlasmicAddEntry__VariantMembers = {};

export type PlasmicAddEntry__VariantsArgs = {};
type VariantPropType = keyof PlasmicAddEntry__VariantsArgs;
export const PlasmicAddEntry__VariantProps = new Array<VariantPropType>();

export type PlasmicAddEntry__ArgsType = {
  test?: any;
  id?: string;
};

type ArgPropType = keyof PlasmicAddEntry__ArgsType;
export const PlasmicAddEntry__ArgProps = new Array<ArgPropType>("test", "id");

export type PlasmicAddEntry__OverridesType = {
  root?: p.Flex<"div">;
  h3?: p.Flex<"h3">;
  supabaseMutation?: p.Flex<typeof SupabaseMutation>;
  formContext?: p.Flex<typeof FormContextComponent>;
  textarea?: p.Flex<"textarea">;
};

export interface DefaultAddEntryProps {}

export const defaultAddEntry__Args: Partial<PlasmicAddEntry__ArgsType> = {};

function PlasmicAddEntry__RenderFunc(props: {
  variants: PlasmicAddEntry__VariantsArgs;
  args: PlasmicAddEntry__ArgsType;
  overrides: PlasmicAddEntry__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultAddEntry__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_52Cioa0UnGfvY1(),
  });

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          {true ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__ojzOi)}
            >
              <h3
                data-plasmic-name={"h3"}
                data-plasmic-override={overrides.h3}
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3
                )}
              >
                {"Ajouter un vélo"}
              </h3>

              <SupabaseMutation
                data-plasmic-name={"supabaseMutation"}
                data-plasmic-override={overrides.supabaseMutation}
                className={classNames("__wab_instance", sty.supabaseMutation)}
                data={{
                  name: "{{form.name}}",
                  description: "{{form.description}}",
                  imageUrl: "{{form.imageUrl}}",
                }}
                method={"insert" as const}
                redirectOnSuccess={"/" as const}
                tableName={"entries" as const}
              >
                <FormContextComponent
                  data-plasmic-name={"formContext"}
                  data-plasmic-override={overrides.formContext}
                  className={classNames("__wab_instance", sty.formContext)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__nAlHg)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__vqtqi)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___48ESq
                        )}
                      >
                        {"Titre"}
                      </div>

                      <FormTextInput
                        className={classNames(
                          "__wab_instance",
                          sty.formTextInput__f0Hi
                        )}
                        name={"name" as const}
                      >
                        <TextInput
                          className={classNames(
                            "__wab_instance",
                            sty.textInput__x4Moy
                          )}
                          placeholder={"Vélo de ville ..." as const}
                          type={"" as const}
                        />
                      </FormTextInput>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__xziVb)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__s80C4
                        )}
                      >
                        {"Image URL"}
                      </div>

                      <FormTextInput
                        className={classNames(
                          "__wab_instance",
                          sty.formTextInput__x8Ip5
                        )}
                        name={"imageUrl" as const}
                      >
                        <TextInput
                          className={classNames(
                            "__wab_instance",
                            sty.textInput__gfgis
                          )}
                          placeholder={"https://picsum.photos/200" as const}
                        />
                      </FormTextInput>
                    </p.Stack>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__g5Krs)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___8Oro
                        )}
                      >
                        {"Description"}
                      </div>

                      <FormTextInput
                        className={classNames(
                          "__wab_instance",
                          sty.formTextInput__xhAe5
                        )}
                        name={"description" as const}
                      >
                        <textarea
                          data-plasmic-name={"textarea"}
                          data-plasmic-override={overrides.textarea}
                          className={classNames(
                            projectcss.all,
                            projectcss.textarea,
                            sty.textarea
                          )}
                          placeholder={"" as const}
                        />
                      </FormTextInput>
                    </div>

                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rgvI
                        )}
                      >
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__gfHyM
                          )}
                          link={"/" as const}
                        >
                          {"Annuler"}
                        </Button>

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button___3H02E
                          )}
                          color={"green" as const}
                        >
                          {"Ajouter"}
                        </Button>
                      </div>
                    ) : null}
                  </p.Stack>
                </FormContextComponent>
              </SupabaseMutation>
            </p.Stack>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h3", "supabaseMutation", "formContext", "textarea"],
  h3: ["h3"],
  supabaseMutation: ["supabaseMutation", "formContext", "textarea"],
  formContext: ["formContext", "textarea"],
  textarea: ["textarea"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  h3: "h3";
  supabaseMutation: typeof SupabaseMutation;
  formContext: typeof FormContextComponent;
  textarea: "textarea";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAddEntry__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAddEntry__VariantsArgs;
    args?: PlasmicAddEntry__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAddEntry__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAddEntry__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAddEntry__ArgProps,
      internalVariantPropNames: PlasmicAddEntry__VariantProps,
    });

    return PlasmicAddEntry__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAddEntry";
  } else {
    func.displayName = `PlasmicAddEntry.${nodeName}`;
  }
  return func;
}

export const PlasmicAddEntry = Object.assign(
  // Top-level PlasmicAddEntry renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h3: makeNodeComponent("h3"),
    supabaseMutation: makeNodeComponent("supabaseMutation"),
    formContext: makeNodeComponent("formContext"),
    textarea: makeNodeComponent("textarea"),

    // Metadata about props expected for PlasmicAddEntry
    internalVariantProps: PlasmicAddEntry__VariantProps,
    internalArgProps: PlasmicAddEntry__ArgProps,
  }
);

export default PlasmicAddEntry;
/* prettier-ignore-end */
