// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uQ1tStPUiuweYuxMksqyYP
// Component: _URXLOJYdHqND
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";
import { SupabaseUserSession } from "../../CodeComponents/DatabaseComponents"; // plasmic-import: AIwu2cAmNNaSa1/codeComponent
import { SupabaseTextField } from "../../CodeComponents/DisplayCollections"; // plasmic-import: RN0SfBGtQkQfm6/codeComponent
import { SupabaseUserLogOut } from "../../CodeComponents/DatabaseComponents"; // plasmic-import: NdigdqWPA1YH0M/codeComponent
import Button from "../../Button"; // plasmic-import: IELNbHKEGo49X/component

import { useScreenVariants as useScreenVariants_52Cioa0UnGfvY1 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 52cioa0UNGfvY1/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_supabase_tutorial_refreshed.module.css"; // plasmic-import: uQ1tStPUiuweYuxMksqyYP/projectcss
import sty from "./PlasmicNavBar.module.css"; // plasmic-import: _URXLOJYdHqND/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: DGsq-C17D8eHoS/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: bpL7QDrSKQF7Lo/icon

export type PlasmicNavBar__VariantMembers = {
  onCompletedGallery: "onCompletedGallery";
};

export type PlasmicNavBar__VariantsArgs = {
  onCompletedGallery?: SingleBooleanChoiceArg<"onCompletedGallery">;
};

type VariantPropType = keyof PlasmicNavBar__VariantsArgs;
export const PlasmicNavBar__VariantProps = new Array<VariantPropType>(
  "onCompletedGallery"
);

export type PlasmicNavBar__ArgsType = {};
type ArgPropType = keyof PlasmicNavBar__ArgsType;
export const PlasmicNavBar__ArgProps = new Array<ArgPropType>();

export type PlasmicNavBar__OverridesType = {
  root?: p.Flex<"div">;
  link?: p.Flex<"a"> & Partial<LinkProps>;
  supabaseUserSession?: p.Flex<typeof SupabaseUserSession>;
  supabaseTextField?: p.Flex<typeof SupabaseTextField>;
  supabaseUserLogOut?: p.Flex<typeof SupabaseUserLogOut>;
  button?: p.Flex<typeof Button>;
};

export interface DefaultNavBarProps {
  onCompletedGallery?: SingleBooleanChoiceArg<"onCompletedGallery">;
  className?: string;
}

export const defaultNavBar__Args: Partial<PlasmicNavBar__ArgsType> = {};

function PlasmicNavBar__RenderFunc(props: {
  variants: PlasmicNavBar__VariantsArgs;
  args: PlasmicNavBar__ArgsType;
  overrides: PlasmicNavBar__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultNavBar__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_52Cioa0UnGfvY1(),
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [sty.rootonCompletedGallery]: hasVariant(
            variants,
            "onCompletedGallery",
            "onCompletedGallery"
          ),
        }
      )}
    >
      <p.PlasmicLink
        data-plasmic-name={"link"}
        data-plasmic-override={overrides.link}
        className={classNames(
          projectcss.all,
          projectcss.a,
          projectcss.__wab_text,
          sty.link
        )}
        component={Link}
        href={"/" as const}
        platform={"nextjs"}
      >
        {"Location de vélos entre particuliers "}
      </p.PlasmicLink>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__x2QoU, {
          [sty.freeBoxonCompletedGallery__x2QoUdgiDs]: hasVariant(
            variants,
            "onCompletedGallery",
            "onCompletedGallery"
          ),
        })}
      >
        {true ? (
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__cfnGw, {
              [sty.freeBoxonCompletedGallery__cfnGwdgiDs]: hasVariant(
                variants,
                "onCompletedGallery",
                "onCompletedGallery"
              ),
            })}
          >
            {(
              hasVariant(variants, "onCompletedGallery", "onCompletedGallery")
                ? true
                : true
            ) ? (
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mMppW,
                  {
                    [sty.textonCompletedGallery__mMppWdgiDs]: hasVariant(
                      variants,
                      "onCompletedGallery",
                      "onCompletedGallery"
                    ),
                  }
                )}
              >
                {"Bonjour, "}
              </div>
            ) : null}

            <SupabaseUserSession
              data-plasmic-name={"supabaseUserSession"}
              data-plasmic-override={overrides.supabaseUserSession}
              className={classNames("__wab_instance", sty.supabaseUserSession)}
            >
              <SupabaseTextField
                data-plasmic-name={"supabaseTextField"}
                data-plasmic-override={overrides.supabaseTextField}
                className={classNames("__wab_instance", sty.supabaseTextField)}
                name={"{{session.email}}" as const}
              />
            </SupabaseUserSession>
          </p.Stack>
        ) : null}

        <SupabaseUserLogOut
          data-plasmic-name={"supabaseUserLogOut"}
          data-plasmic-override={overrides.supabaseUserLogOut}
          className={classNames("__wab_instance", sty.supabaseUserLogOut)}
          redirectOnSuccess={"/login-page" as const}
        >
          <Button
            data-plasmic-name={"button"}
            data-plasmic-override={overrides.button}
            className={classNames("__wab_instance", sty.button)}
            shape={"bordered" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__wk78S
              )}
            >
              {"Déconnexion"}
            </div>
          </Button>
        </SupabaseUserLogOut>
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "link",
    "supabaseUserSession",
    "supabaseTextField",
    "supabaseUserLogOut",
    "button",
  ],
  link: ["link"],
  supabaseUserSession: ["supabaseUserSession", "supabaseTextField"],
  supabaseTextField: ["supabaseTextField"],
  supabaseUserLogOut: ["supabaseUserLogOut", "button"],
  button: ["button"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  link: "a";
  supabaseUserSession: typeof SupabaseUserSession;
  supabaseTextField: typeof SupabaseTextField;
  supabaseUserLogOut: typeof SupabaseUserLogOut;
  button: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavBar__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavBar__VariantsArgs;
    args?: PlasmicNavBar__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNavBar__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicNavBar__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNavBar__ArgProps,
      internalVariantPropNames: PlasmicNavBar__VariantProps,
    });

    return PlasmicNavBar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavBar";
  } else {
    func.displayName = `PlasmicNavBar.${nodeName}`;
  }
  return func;
}

export const PlasmicNavBar = Object.assign(
  // Top-level PlasmicNavBar renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),
    supabaseUserSession: makeNodeComponent("supabaseUserSession"),
    supabaseTextField: makeNodeComponent("supabaseTextField"),
    supabaseUserLogOut: makeNodeComponent("supabaseUserLogOut"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicNavBar
    internalVariantProps: PlasmicNavBar__VariantProps,
    internalArgProps: PlasmicNavBar__ArgProps,
  }
);

export default PlasmicNavBar;
/* prettier-ignore-end */
