// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uQ1tStPUiuweYuxMksqyYP
// Component: tjDGBiuBQL-Qm
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";
import { SupabaseEditButton } from "../../CodeComponents/UtilsComponents"; // plasmic-import: Ul0_n79AI7BZ7d/codeComponent
import Button from "../../Button"; // plasmic-import: IELNbHKEGo49X/component
import { SupabaseDeleteButton } from "../../CodeComponents/UtilsComponents"; // plasmic-import: Xj0xiZm97ZmiDp/codeComponent
import { SupabaseMutation } from "../../CodeComponents/DatabaseComponents"; // plasmic-import: -f1Kq0-fPBNYLK/codeComponent
import { SupabaseModal } from "../../CodeComponents/UtilsComponents"; // plasmic-import: YQpDcYc8zDO5Pn/codeComponent
import { SupabaseTextField } from "../../CodeComponents/DisplayCollections"; // plasmic-import: RN0SfBGtQkQfm6/codeComponent
import { SupabaseImgField } from "../../CodeComponents/DisplayCollections"; // plasmic-import: rF1A-J4iicPi5b/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_supabase_tutorial_refreshed.module.css"; // plasmic-import: uQ1tStPUiuweYuxMksqyYP/projectcss
import sty from "./PlasmicPost.module.css"; // plasmic-import: tjDGBiuBQL-Qm/css

import EditIcon from "./icons/PlasmicIcon__Edit"; // plasmic-import: suBvJwr0Ww3-mq/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: bpL7QDrSKQF7Lo/icon
import DeleteIcon from "./icons/PlasmicIcon__Delete"; // plasmic-import: xN2AyMzwK-27Uz/icon

export type PlasmicPost__VariantMembers = {};

export type PlasmicPost__VariantsArgs = {};
type VariantPropType = keyof PlasmicPost__VariantsArgs;
export const PlasmicPost__VariantProps = new Array<VariantPropType>();

export type PlasmicPost__ArgsType = {
  title?: React.ReactNode;
  description?: React.ReactNode;
  image?: React.ReactNode;
};

type ArgPropType = keyof PlasmicPost__ArgsType;
export const PlasmicPost__ArgProps = new Array<ArgPropType>(
  "title",
  "description",
  "image"
);

export type PlasmicPost__OverridesType = {
  root?: p.Flex<"div">;
  supabaseEditButton?: p.Flex<typeof SupabaseEditButton>;
  supabaseDeleteButton?: p.Flex<typeof SupabaseDeleteButton>;
  supabaseMutation?: p.Flex<typeof SupabaseMutation>;
  supabaseModal?: p.Flex<typeof SupabaseModal>;
  supabaseImgField?: p.Flex<typeof SupabaseImgField>;
};

export interface DefaultPostProps {
  title?: React.ReactNode;
  description?: React.ReactNode;
  image?: React.ReactNode;
  className?: string;
}

export const defaultPost__Args: Partial<PlasmicPost__ArgsType> = {};

function PlasmicPost__RenderFunc(props: {
  variants: PlasmicPost__VariantsArgs;
  args: PlasmicPost__ArgsType;
  overrides: PlasmicPost__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultPost__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      {true ? (
        <div className={classNames(projectcss.all, sty.freeBox___1Feja)}>
          {p.renderPlasmicSlot({
            defaultContents: true ? (
              <div className={classNames(projectcss.all, sty.freeBox__bZaOb)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__oWx5F)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                />
              </div>
            ) : null,
            value: args.image,
          })}
        </div>
      ) : null}
      {true ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__cs6Bh)}
        >
          {true ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__ceEzx)}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kkC7C
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Title"}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                ),

                value: args.title,
              })}

              {p.renderPlasmicSlot({
                defaultContents: "Description",
                value: args.description,
                className: classNames(sty.slotTargetDescription),
              })}
            </p.Stack>
          ) : null}
          {true ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__nqcA)}
            >
              <SupabaseEditButton
                data-plasmic-name={"supabaseEditButton"}
                data-plasmic-override={overrides.supabaseEditButton}
                className={classNames("__wab_instance", sty.supabaseEditButton)}
                editPage={"/post/update/id" as const}
                id={"{{row.id}}" as const}
              >
                <Button
                  className={classNames("__wab_instance", sty.button__nhVS)}
                  hideLabel={true}
                  shape={"bordered" as const}
                  showStartIcon={true}
                  startIcon={
                    <EditIcon
                      className={classNames(projectcss.all, sty.svg__zdLix)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___56A
                    )}
                  >
                    {"Edit"}
                  </div>
                </Button>
              </SupabaseEditButton>

              <SupabaseDeleteButton
                data-plasmic-name={"supabaseDeleteButton"}
                data-plasmic-override={overrides.supabaseDeleteButton}
                className={classNames(
                  "__wab_instance",
                  sty.supabaseDeleteButton
                )}
                id={"{{row.id}}" as const}
                modal={
                  <SupabaseMutation
                    data-plasmic-name={"supabaseMutation"}
                    data-plasmic-override={overrides.supabaseMutation}
                    className={classNames(
                      "__wab_instance",
                      sty.supabaseMutation
                    )}
                    filters={[
                      {
                        name: "eq",
                        args: [{ column: "id", value: "{{local.id}}" }],
                      },
                    ]}
                    method={"delete" as const}
                    redirectOnSuccess={"/" as const}
                    tableName={"posts" as const}
                  >
                    <SupabaseModal
                      data-plasmic-name={"supabaseModal"}
                      data-plasmic-override={overrides.supabaseModal}
                      className={classNames(
                        "__wab_instance",
                        sty.supabaseModal
                      )}
                      showModal={false}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__jtWck
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vbOd
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__mWtXx
                            )}
                          >
                            {"Title"}
                          </div>

                          <SupabaseTextField
                            className={classNames(
                              "__wab_instance",
                              sty.supabaseTextField__yyi39
                            )}
                            name={"{{row.title}}" as const}
                          />
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__xxKt
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__x2Atr
                            )}
                          >
                            {"Content"}
                          </div>

                          <SupabaseTextField
                            className={classNames(
                              "__wab_instance",
                              sty.supabaseTextField__c9Hj
                            )}
                            name={"{{row.content}}" as const}
                          />
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__s81No
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__m6Gse
                            )}
                          >
                            {"Image"}
                          </div>

                          {true ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__fG1V2
                              )}
                            >
                              <SupabaseImgField
                                data-plasmic-name={"supabaseImgField"}
                                data-plasmic-override={
                                  overrides.supabaseImgField
                                }
                                className={classNames(
                                  "__wab_instance",
                                  sty.supabaseImgField
                                )}
                                url={"{{row.imageUrl}}" as const}
                              />
                            </div>
                          ) : null}
                        </p.Stack>
                      </div>
                    </SupabaseModal>
                  </SupabaseMutation>
                }
              >
                <Button
                  className={classNames("__wab_instance", sty.button__xUn5N)}
                  hideLabel={true}
                  shape={"borderedRedOnHover" as const}
                  showStartIcon={true}
                  startIcon={
                    <DeleteIcon
                      className={classNames(projectcss.all, sty.svg__lR5Vc)}
                      role={"img"}
                    />
                  }
                />
              </SupabaseDeleteButton>
            </p.Stack>
          ) : null}
        </p.Stack>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "supabaseEditButton",
    "supabaseDeleteButton",
    "supabaseMutation",
    "supabaseModal",
    "supabaseImgField",
  ],
  supabaseEditButton: ["supabaseEditButton"],
  supabaseDeleteButton: [
    "supabaseDeleteButton",
    "supabaseMutation",
    "supabaseModal",
    "supabaseImgField",
  ],
  supabaseMutation: ["supabaseMutation", "supabaseModal", "supabaseImgField"],
  supabaseModal: ["supabaseModal", "supabaseImgField"],
  supabaseImgField: ["supabaseImgField"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  supabaseEditButton: typeof SupabaseEditButton;
  supabaseDeleteButton: typeof SupabaseDeleteButton;
  supabaseMutation: typeof SupabaseMutation;
  supabaseModal: typeof SupabaseModal;
  supabaseImgField: typeof SupabaseImgField;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPost__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPost__VariantsArgs;
    args?: PlasmicPost__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPost__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPost__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPost__ArgProps,
      internalVariantPropNames: PlasmicPost__VariantProps,
    });

    return PlasmicPost__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPost";
  } else {
    func.displayName = `PlasmicPost.${nodeName}`;
  }
  return func;
}

export const PlasmicPost = Object.assign(
  // Top-level PlasmicPost renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    supabaseEditButton: makeNodeComponent("supabaseEditButton"),
    supabaseDeleteButton: makeNodeComponent("supabaseDeleteButton"),
    supabaseMutation: makeNodeComponent("supabaseMutation"),
    supabaseModal: makeNodeComponent("supabaseModal"),
    supabaseImgField: makeNodeComponent("supabaseImgField"),

    // Metadata about props expected for PlasmicPost
    internalVariantProps: PlasmicPost__VariantProps,
    internalArgProps: PlasmicPost__ArgProps,
  }
);

export default PlasmicPost;
/* prettier-ignore-end */
